version: '3.9'

services:
  # Дали название сервису
  flask_app:
    # Указали путь до Dockerfile
    build: .
    # Указали по какому порту запускать сервис
    ports:
      - "8000:8000"
    # Указываем что сначала запускаем БД 'db', а уже потом собираем наш контейнер flask_app
    depends_on:
      - db
    networks:
      - backend

  db:
    # Берем готовый образ с DockerHub для PosgreSQL
    image: postgres:14.8-alpine3.18
    # Вносим переменные окружения и задаем настройки для логирования
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data
    # Указываем путь где мы будем хранить данные(временное хранилище) в момент перезапуска БД
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

# Объединяем 2 сервиса в сети network
networks:
  backend:
# Инициализируем том pgdata, что позволяет сохранять данные между запусками контейнеров
volumes:
  pgdata:
